### ISSUE TITLE
Is there a leaderboard for the best performance of each method with corresponding hyperparameters?

### ISSUE THREAD

**Issue by Lily-Le** [LINs-lab/ttab#13]
Hi. Thanks for the fantastic work. :D . Is there a leaderboard for each setting to show the performance of each method along with the corresponding hyperparameters? Or is there a way to submit the tuned results?

Thanks a lot.

**Comment by MarcellusZhao** [comment]
Hi, 

Thanks for your interest in our work! 

> Is there a leaderboard for each setting to show the performance of each method along with the corresponding hyperparameters?

It's a great idea! We are thinking of adding a leaderboard to our repository so that everyone can easily keep track of the performance of state-of-the-arts. But we are a bit busy recently, we will organize results in the form of leaderboard and make it public later. Stay tuned :)

> Or is there a way to submit the tuned results?

Sorry, this repo does not yet support the submission of tuned results. We will discuss and respond to this request asap.

**Comment by Lily-Le** [comment]
Thanks for your reply. :D
