### ISSUE TITLE
The experimental results in TTAB are inconsistent with the original results in CoTTA

### ISSUE THREAD

**Issue by AAAI-2025** [LINs-lab/ttab#2]
In TTAB, we trained WideResnet28*10 with Cifar-10, which is also used in the original paper of CoTTA.   Nevertheless,  the accuracy of using CoTTA to predict data Snow-5 is 51% in TTAB; the accuracy of using CoTTA to predict data Snow-5 is 85% in the original paper.  So why there is a huge gap between the two results?

**Comment by MarcellusZhao** [comment]
Hello, thanks for your attention on our work.

- First of all, we checked our implementation through directly comparing the performance of our implementation to that of the original repository under the same experimental setting (i.e., using the same ResNet-26 model checkpoint and same hyperparameters with the original paper). More details of implementation checking are shown below.
<img width="1171" alt="CleanShot 2023-07-26 at 07 22 13@2x" src="https://github.com/LINs-lab/ttab/assets/50657356/2b947aca-031b-4927-87ce-9b30a730dfd8">

- Secondly, our goal is to compare prior TTA methods as fair as possible, so we adjust part of the implementation in a reasonable way to make it consistent with other methods. According to my experience, the gap regarding CoTTA between the original work and our work is mainly due to the normalization transform applied to the input image. If I remember correctly, the original implementation does not use `transforms.normalize`. You can quickly check it out on their repo, and verify its influence by adding a `normalize` transform, or remove the `normalize` used in TTAB).

**Comment by MarcellusZhao** [comment]
Hello, thanks again for you interest!
Does my answer resolve your concern? If yes, can I close this issue?

**Comment by AAAI-2025** [comment]
Hello，sorry for not replying in time. Recently, the  server in our school was shut down due to cooling problem. So we haven't debugged the code yet.  You can close the issue first. If I have any questions later, can I consult you by email? Thanks again for your careful reply.
Best wishes

**Comment by MarcellusZhao** [comment]
Sure!

**Comment by walawalagoose** [comment]
> In TTAB, we trained WideResnet28*10 with Cifar-10, which is also used in the original paper of CoTTA. Nevertheless, the accuracy of using CoTTA to predict data Snow-5 is 51% in TTAB; the accuracy of using CoTTA to predict data Snow-5 is 85% in the original paper. So why there is a huge gap between the two results?

Hey, I've also encountered this problem recently. May I ask if u have sloved this problem yet?
