### ISSUE TITLE
The unexpected error of training resnet and wideresnet on imageNet dataset.

### ISSUE THREAD

**Issue by UnknownX1** [LINs-lab/ttab#3]
I want to train resnet18 on ImageNet datasets.
And I change class `CIFARDataset` into `ImageNetDataset` in `pretrain_self_supervised_cifar10.py` file.
Here is my config
```
config = {
    # general
    "seed": 2022,
    "ckpt_path": "/data/TTA-exp/ttab/pretrain/ckpt",
    "device": "cuda:0",
    "log_dir": "/data/TTA-exp/ttab/data/runs",
    # data
    "data_path": "/data/TTA-exp/ttab/datasets",
    "data_name": "imagenet",
    "num_classes": 15,
    # model
    "model_name": "resnet18",
    "task_name": "classification",
    "resume": False,
    # hyperparams
    "entry_of_shared_layers": "layer3",
    "dim_out": 4,
    "use_iabn": False,
    "iabn_k": 4,
    "use_ls": True,  # label smoothing: https://arxiv.org/abs/1906.02629
    "threshold_note": 1,
    "rotation_type": "expand",
    "lr": 0.1,
    "momentum": 0.9,
    "weight_decay": 5e-4,
    "maxEpochs": 150,
    "milestones": [75, 125],
    "batch_size": 128,
    "save_epoch": 10,  # save weights file per SAVE_EPOCH epoch.
}
```
When we are training resnet18 on ImageNet dataset.
We get this error.
![2f43006757be838a0d1be249fe7dd85](https://github.com/LINs-lab/ttab/assets/56467082/70131e77-546c-42d5-883f-9293bbaa3a5d)

And then we change line 310 in ttab/loads/models/resnet.py `self.avgpool = nn.AvgPool2d(kernel_size=7, stride=1)` into `self.avgpool = nn.AvgPool2d(kernel_size=1, stride=1)`, then we get this error.
![27fa018cd360690e066071c7098e49e](https://github.com/LINs-lab/ttab/assets/56467082/270f46a6-6bfd-489f-b7e2-83d3b9842e5d)

Moreover, We used the model `widerest28_10` still get this error.
![ea68ba75f61ff2a173e1bba3a788877](https://github.com/LINs-lab/ttab/assets/56467082/c359cdbc-9e2b-4962-8ef3-01e230178d7c)

**Comment by MarcellusZhao** [comment]
Hello, thanks for your interest in our work!
To answer your questions:
- I didn't use `pretrain_self_supervised_cifar10.py` to pretrain a model on ImageNet before, so it's not surprising seeing it cannot work. I guess this error arises because of `SelfSupervisedModel` or the `ResNet18` itself. We have a plan to maintain this codebase right now, but giving a script pretraining on ImageNet dataset from scratch is not a priority due to our limited computational resource.
- I see there are some public checkpoints pretrained on ImageNet dataset, even ResNet-18 as per your request, such as PyTorch ([ResNets](https://pytorch.org/vision/stable/models/resnet.html), [WideResNets](https://pytorch.org/vision/stable/models/wide_resnet.html)) and [HuggingFace](https://huggingface.co/models?dataset=dataset:imagenet). Some of them are used in our project.

If these public pretrained checkpoints cannot meet your needs, I can have a look at it over the weekend. Just let me know whether this answer resolves your issue or not:)

**Comment by MarcellusZhao** [comment]
Hello,

Does my answer meet your needs? If yes, I would like to close this issue. More comments and questions are more than welcome!

**Comment by UnknownX1** [comment]
Hello, sorry for not replying in time. Thank you for your response! Your answer does meet my needs, and I appreciate your assistance. If I have any questions later, I will consult you again!
